version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"  # map container 8000 to host 8001
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:80"  # map container 80 to host 8080
    depends_on:
      - backend

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: