FROM nginx:alpine

# Copy nginx configuration
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# If you're using default.conf too, include this line:
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy static files from your frontend build
COPY ./dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]